/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PayMachine__factory } from "./PayMachine__factory";
export { SomeToken__factory } from "./SomeToken__factory";
